# Check out https://docs.codemagic.io/getting-started/yaml/ for more information

workflows:
  my-workflow:
    name: Flutter Test
    environment:
      flutter: dev
    triggering:
      events:                       # List the events that trigger builds
        - push
        - pull_request
      branch_patterns:              # Include or exclude watched branches
        - pattern: 'main'
          include: true
          source: false             # mainに対するPR更新
          cancel_previous_builds: true  # Set to `true` to automatically cancel outdated webhook builds
        - pattern: 'develop'
          include: true
          source: false                 # developに対するPR更新
          cancel_previous_builds: true  # Set to `true` to automatically cancel outdated webhook builds
    scripts:
      - name: make .env file
        script: cp flutter_eikan/.env.example flutter_eikan/.env
      - name: package install
        script: cd flutter_eikan && flutter packages pub get
      - name: flutter test
        script: cd flutter_eikan && flutter test
    artifacts:
      - flutter_drive.log
    publishing:
      slack:
        channel: '#general'
        notify_on_build_start: false    # To receive a notification when a build starts
        notify:
          success: true               # To not receive a notification when a build succeeds
          failure: true