# Check out https://docs.codemagic.io/getting-started/yaml/ for more information

workflows:
    flutter-widget:
        name: Flutter Widget
        environment:
            vars:

            flutter: dev
        scripts:
            - cp flutter_eikan/.env.example flutter_eikan/.env
            - |
                cd flutter_eikan \
                && flutter packages pub get \
                && flutter test