# Check out https://docs.codemagic.io/getting-started/yaml/ for more information

workflows:
    flutter-widget:
        name: Flutter Widget
        environment:
            flutter: dev
        scripts:
            - cd flutter_eikan
            - flutter packages pub get
            - flutter test