# Check out https://docs.codemagic.io/getting-started/yaml/ for more information

workflows:
  my-workflow:
    name: Flutter Test
    environment:
      flutter: stable
    triggering:
      events:                       # List the events that trigger builds
        - pull_request
      branch_patterns:              # Include or exclude watched branches
        - pattern: 'develop'
          include: true
          source: true
          cancel_previous_builds: true  # Set to `true` to automatically cancel outdated webhook builds
    scripts:
      - name: make .env file
        script: cp flutter_eikan/.env.example flutter_eikan/.env
      - name: package install & flutter test
        script: |
          cd flutter_eikan \
          && flutter packages pub get \
          && flutter test
    artifacts:
      - flutter_drive.log
    publishing:
      slack:
        channel: '#general'
        notify_on_build_start: false    # To receive a notification when a build starts
        notify:
          success: true               # To not receive a notification when a build succeeds
          failure: true