# https://circleci.com/docs/ja/2.0/language-go/
# https://o296.com/2019/10/13/Circle.html
# $ circleci config validate
# $ circleci execute

version: 2.1
orbs:
  slack: circleci/slack@4.2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.15

    steps:
      - checkout
      - restore_cache:
          keys:
            - mod-{{ checksum "golang_eikan/go.sum" }}
            # https://circleci.com/docs/ja/2.0/caching/
            # 公式では go.sum をコミットすべきらしい。
            # https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file

      - run: cp golang_eikan/configs/config.example.ini golang_eikan/configs/config.ini
      - run: cd golang_eikan && go get
      - run: cd golang_eikan && go test -v ./...

      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - slack/notify:
          event: fail
          template: basic_fail_1

      - save_cache:
          key: mod-{{ checksum "golang_eikan/go.sum" }}
          paths:
            - $GOPATH/pkg/mod
            # $GOPATH == /go
            # ls $GOPATH/pkg/mod
            # => cache  github.com  go.mongodb.org  golang.org  gopkg.in

  # notify:
  #   docker:
  #     - image: 'cimg/base:stable'
  #   steps:
  #     - slack/notify:
  #         event: pass
  #         template: success_tagged_deploy_1
  #     - slack/notify:
  #         event: fail
  #         template: basic_fail_1